export const seniorEaseColorValues = {
  primary: '#1c1c1e',
  onPrimary: '#ffffff',
  canvas: '#ffffff',
  surface: '#f7f8fa',
  surfaceSoft: '#fafbfc',
  hairline: '#e0e2e8',
  hairlineSoft: '#eef0f3',
  hairlineStrong: '#c7cad5',
  inkDeep: '#050038',
  ink: '#1c1c1e',
  charcoal: '#2c2c34',
  slate: '#555a6a',
  steel: '#6b6f7e',
  muted: '#a5a8b5',
  brandBlue: '#4262ff',
  blue450: '#5b76fe',
  bluePressed: '#2a41b6',
  brandYellow: '#ffd02f',
  yellowLight: '#fff4c4',
  yellowSoft: '#fff8e0',
  yellowBorder: '#fcb900',
  yellowDark: '#746019',
  brandTeal: '#0fbcb0',
  tealLight: '#c3faf5',
  mossDark: '#187574',
  brandRed: '#fbd4d4',
  brandRedDark: '#e3c5c5',
  coralDark: '#600000',
  successAccent: '#00b473',
} as const

export const mobileHighContrastTokens = {
  screenBackground: '#FFFFFF',
  cardBackground: '#FFFFFF',
  cardBorder: '#000000',
  chipBackground: '#FFFFFF',
  chipSelectedBackground: '#000000',
  chipText: '#000000',
  chipSelectedText: '#FFFFFF',
  textPrimary: '#000000',
  textSecondary: '#111111',
  primaryButtonBackground: '#000000',
  primaryButtonText: '#FFFFFF',
  warningSurface: '#FFF7B2',
  warningText: '#000000',
  successSurface: '#D9FBE1',
  successBorder: '#0B6E2B',
  dangerSurface: '#FFE3E0',
  dangerBorder: '#8A0000',
  dangerText: '#000000',
  topBarBrandBackground: '#000000',
  topBarActionBackground: '#FFD400',
  topBarActionText: '#000000',
  focus: '#000000',
  focusHalo: '#FFD400',
  interactiveBorder: '#000000',
  disabledBackground: '#E5E5E5',
  disabledText: '#595959',
  primaryHover: '#2B2B2B',
  secondaryHover: '#E5E5E5',
  completionHover: '#E0B800',
  infoSurface: '#FFFFFF',
  infoBorder: '#000000',
} as const

export const seniorEaseColorVariableNames = {
  primary: '--seniorease-primary',
  onPrimary: '--seniorease-selected-text',
  canvas: '--seniorease-canvas',
  surface: '--seniorease-surface',
  surfaceSoft: '--seniorease-surface-soft',
  hairline: '--seniorease-card-border',
  hairlineSoft: '--seniorease-frame-border',
  hairlineStrong: '--seniorease-control-border',
  inkDeep: '--seniorease-ink-deep',
  ink: '--seniorease-ink',
  charcoal: '--seniorease-charcoal',
  slate: '--seniorease-slate',
  steel: '--seniorease-steel',
  muted: '--seniorease-muted',
  brandBlue: '--seniorease-selected-background',
  blue450: '--seniorease-blue-450',
  bluePressed: '--seniorease-blue-pressed',
  brandYellow: '--seniorease-brand-yellow',
  yellowLight: '--seniorease-yellow-light',
  yellowSoft: '--seniorease-yellow-soft',
  yellowBorder: '--seniorease-yellow-border',
  yellowDark: '--seniorease-yellow-dark',
  brandTeal: '--seniorease-brand-teal',
  tealLight: '--seniorease-success-surface',
  mossDark: '--seniorease-success-text',
  brandRed: '--seniorease-danger-surface',
  brandRedDark: '--seniorease-danger-hover',
  coralDark: '--seniorease-danger-text',
  successAccent: '--seniorease-success-accent',
  focus: '--seniorease-focus',
  focusHalo: '--seniorease-focus-halo',
  interactiveBorder: '--seniorease-interactive-border',
  disabledBackground: '--seniorease-disabled-background',
  disabledText: '--seniorease-disabled-text',
  primaryHover: '--seniorease-primary-hover',
  secondaryHover: '--seniorease-secondary-hover',
  completionHover: '--seniorease-completion-hover',
} as const

type SeniorEaseColorVariable = keyof typeof seniorEaseColorVariableNames

export type SeniorEaseResolvedColors = Record<
  SeniorEaseColorVariable,
  string
>

const seniorEaseColorVars = Object.fromEntries(
  Object.entries(seniorEaseColorVariableNames).map(([name, variableName]) => [
    name,
    `var(${variableName})`,
  ]),
) as Record<SeniorEaseColorVariable, string>

export const designTokens = {
  colorValues: seniorEaseColorValues,
  colors: seniorEaseColorVars,
  typography: {
    fontFamily: '"Inter", "Noto Sans", system-ui, sans-serif',
    h1: { fontSize: 36, fontWeight: 600, lineHeight: 1.4 },
    h2: { fontSize: 26, fontWeight: 600, lineHeight: 1.4 },
    h3: { fontSize: 24, fontWeight: 600, lineHeight: 1.4 },
    h4: { fontSize: 22, fontWeight: 600, lineHeight: 1.4 },
    h5: { fontSize: 18, fontWeight: 600, lineHeight: 1.4 },
    subtitle: { fontSize: 18, fontWeight: 400, lineHeight: 1.4 },
    body: { fontSize: 16, fontWeight: 400, lineHeight: 1.4 },
    bodySmall: { fontSize: 15, fontWeight: 400, lineHeight: 1.4 },
    caption: { fontSize: 14, fontWeight: 500, lineHeight: 1.4 },
    button: { fontSize: 16, fontWeight: 600, lineHeight: 1.4 },
    mobileActivityTitle: { fontSize: 14, fontWeight: 600, lineHeight: 1.4 },
    mobileActivityMeta: { fontSize: 11, fontWeight: 400, lineHeight: 1.4 },
  },
  rounded: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 28,
    xxxl: 28,
    feature: 32,
    full: 9999,
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    controlY: 14,
    md: 16,
    cardGap: 16,
    mobilePage: 18,
    rowPadding: 18,
    lg: 20,
    topBarGap: 22,
    xl: 24,
    tabletPage: 28,
    appFrame: 32,
    xxl: 32,
    xxxl: 40,
    sectionSmall: 48,
    section: 64,
    sectionLarge: 96,
    hero: 120,
  },
  components: {
    appShell: {
      backgroundColor: seniorEaseColorVars.surface,
      borderColor: seniorEaseColorVars.hairlineSoft,
      borderWidth: 1,
      gapDesktop: 28,
      gapTablet: 22,
      gapMobile: 18,
      paddingDesktop: 32,
      paddingTablet: 28,
      paddingMobile: 18,
      radius: 32,
    },
    sideNavigation: {
      backgroundColor: seniorEaseColorVars.primary,
      itemActiveBackgroundColor: seniorEaseColorVars.yellowLight,
      itemInactiveBackgroundColor: seniorEaseColorVars.charcoal,
      itemRadius: 16,
      itemPaddingX: 16,
      itemPaddingY: 12,
      noteBackgroundColor: seniorEaseColorVars.charcoal,
      notePadding: 24,
      noteRadius: 24,
      paddingX: 20,
      paddingY: 28,
      radius: 28,
    },
    topNavigation: {
      backgroundColor: seniorEaseColorVars.primary,
      brandFontSizeTablet: 26,
      brandFontSizeMobile: 21,
      menuBackgroundColor: seniorEaseColorVars.brandYellow,
      menuPaddingX: 14,
      menuPaddingY: 8,
      radiusTablet: 24,
      radiusMobile: 20,
      paddingXTablet: 20,
      paddingYTablet: 16,
      paddingXMobile: 12,
      paddingYMobile: 10,
    },
    card: {
      backgroundColor: seniorEaseColorVars.canvas,
      borderColor: seniorEaseColorVars.hairline,
      gap: 16,
      padding: 24,
      radius: 24,
    },
    activityRow: {
      backgroundColor: seniorEaseColorVars.canvas,
      borderColor: seniorEaseColorVars.hairline,
      gapMobile: 14,
      heightDesktop: 96,
      paddingDesktop: 18,
      paddingMobile: 14,
      radius: 20,
    },
    guidedStep: {
      backgroundColor: seniorEaseColorVars.canvas,
      currentBackgroundColor: seniorEaseColorVars.yellowSoft,
      currentBorderColor: seniorEaseColorVars.yellowBorder,
      gap: 18,
      iconSize: 40,
      padding: 20,
      radius: 22,
    },
    button: {
      borderRadius: 9999,
      minHeight: 52,
      paddingX: 20,
      paddingY: 14,
    },
    pill: {
      borderRadius: 9999,
      paddingX: 16,
      paddingY: 9,
      compactPaddingX: 12,
      compactPaddingY: 8,
    },
    switch: {
      height: 36,
      thumbInset: 4,
      thumbSize: 28,
      width: 64,
    },
  },
} as const

export type SeniorEaseDesignTokens = typeof designTokens
