export const designTokens = {
  colors: {
    primary: '#1c1c1e',
    onPrimary: '#ffffff',
    canvas: '#ffffff',
    surface: '#f7f8fa',
    surfaceSoft: '#fafbfc',
    hairline: '#e0e2e8',
    hairlineSoft: '#eef0f3',
    hairlineStrong: '#c7cad5',
    inkDeep: '#050038',
    ink: '#1c1c1e',
    charcoal: '#2c2c34',
    slate: '#555a6a',
    steel: '#6b6f7e',
    muted: '#a5a8b5',
    brandBlue: '#4262ff',
    blue450: '#5b76fe',
    bluePressed: '#2a41b6',
    brandYellow: '#ffd02f',
    yellowLight: '#fff4c4',
    yellowSoft: '#fff8e0',
    yellowBorder: '#fcb900',
    yellowDark: '#746019',
    brandTeal: '#0fbcb0',
    tealLight: '#c3faf5',
    mossDark: '#187574',
    brandRed: '#fbd4d4',
    brandRedDark: '#e3c5c5',
    coralDark: '#600000',
    successAccent: '#00b473',
  },
  typography: {
    fontFamily: '"Inter", "Noto Sans", system-ui, sans-serif',
    h1: { fontSize: 36, fontWeight: 600, lineHeight: 1.4 },
    h2: { fontSize: 26, fontWeight: 600, lineHeight: 1.4 },
    h3: { fontSize: 24, fontWeight: 600, lineHeight: 1.4 },
    h4: { fontSize: 22, fontWeight: 600, lineHeight: 1.4 },
    h5: { fontSize: 18, fontWeight: 600, lineHeight: 1.4 },
    subtitle: { fontSize: 18, fontWeight: 400, lineHeight: 1.4 },
    body: { fontSize: 16, fontWeight: 400, lineHeight: 1.4 },
    bodySmall: { fontSize: 15, fontWeight: 400, lineHeight: 1.4 },
    caption: { fontSize: 14, fontWeight: 500, lineHeight: 1.4 },
    button: { fontSize: 16, fontWeight: 600, lineHeight: 1.4 },
    mobileActivityTitle: { fontSize: 14, fontWeight: 600, lineHeight: 1.4 },
    mobileActivityMeta: { fontSize: 11, fontWeight: 400, lineHeight: 1.4 },
  },
  rounded: {
    xs: 4,
    sm: 8,
    md: 16,
    lg: 20,
    xl: 24,
    xxl: 28,
    xxxl: 28,
    feature: 32,
    full: 9999,
  },
  spacing: {
    xxs: 4,
    xs: 8,
    sm: 12,
    controlY: 14,
    md: 16,
    cardGap: 16,
    mobilePage: 18,
    rowPadding: 18,
    lg: 20,
    topBarGap: 22,
    xl: 24,
    tabletPage: 28,
    appFrame: 32,
    xxl: 32,
    xxxl: 40,
    sectionSmall: 48,
    section: 64,
    sectionLarge: 96,
    hero: 120,
  },
  components: {
    appShell: {
      backgroundColor: '#f7f8fa',
      borderColor: '#eef0f3',
      borderWidth: 1,
      gapDesktop: 28,
      gapTablet: 22,
      gapMobile: 18,
      paddingDesktop: 32,
      paddingTablet: 28,
      paddingMobile: 18,
      radius: 32,
    },
    sideNavigation: {
      backgroundColor: '#1c1c1e',
      itemActiveBackgroundColor: '#fff4c4',
      itemInactiveBackgroundColor: '#2c2c34',
      itemRadius: 16,
      itemPaddingX: 16,
      itemPaddingY: 12,
      noteBackgroundColor: '#2c2c34',
      notePadding: 24,
      noteRadius: 24,
      paddingX: 20,
      paddingY: 28,
      radius: 28,
    },
    topNavigation: {
      backgroundColor: '#1c1c1e',
      brandFontSizeTablet: 26,
      brandFontSizeMobile: 21,
      menuBackgroundColor: '#ffd02f',
      menuPaddingX: 14,
      menuPaddingY: 8,
      radiusTablet: 24,
      radiusMobile: 20,
      paddingXTablet: 20,
      paddingYTablet: 16,
      paddingXMobile: 12,
      paddingYMobile: 10,
    },
    card: {
      backgroundColor: '#ffffff',
      borderColor: '#e0e2e8',
      gap: 16,
      padding: 24,
      radius: 24,
    },
    activityRow: {
      backgroundColor: '#ffffff',
      borderColor: '#e0e2e8',
      gapMobile: 14,
      heightDesktop: 96,
      paddingDesktop: 18,
      paddingMobile: 14,
      radius: 20,
    },
    guidedStep: {
      backgroundColor: '#ffffff',
      currentBackgroundColor: '#fff8e0',
      currentBorderColor: '#fcb900',
      gap: 18,
      iconSize: 40,
      padding: 20,
      radius: 22,
    },
    button: {
      borderRadius: 9999,
      minHeight: 52,
      paddingX: 20,
      paddingY: 14,
    },
    pill: {
      borderRadius: 9999,
      paddingX: 16,
      paddingY: 9,
      compactPaddingX: 12,
      compactPaddingY: 8,
    },
    switch: {
      height: 36,
      thumbInset: 4,
      thumbSize: 28,
      width: 64,
    },
  },
} as const

export type SeniorEaseDesignTokens = typeof designTokens
